"""
AI Chess Arena - Data Models & Schemas
======================================
This module defines the Pydantic data structures used throughout the application:
- Player configurations (LLM model ID, provider, temperature, thinking mode, system prompt)
- Move data and history tracking
- Board and game state serialization
- API key settings and game control payloads
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any
from enum import Enum


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class GameStatus(str, Enum):
    """Represents the current lifecycle status of a chess match."""
    IDLE = "idle"          # No active match running
    PLAYING = "playing"    # Match actively in progress
    PAUSING = "pausing"    # Match pause requested, completing in-flight active turn
    PAUSED = "paused"      # Match temporarily halted by the user
    FINISHED = "finished"  # Match concluded (checkmate, draw, or resignation)


class PlayerColor(str, Enum):
    """The chess piece colors."""
    WHITE = "white"
    BLACK = "black"


class ProviderType(str, Enum):
    """Supported LLM AI providers."""
    DEEPSEEK = "deepseek"      # Official DeepSeek API
    OPENAI = "openai"          # OpenAI API
    GEMINI = "gemini"          # Google Gemini API
    ANTHROPIC = "anthropic"    # Anthropic API
    GROQ = "groq"              # Groq Cloud
    OPENROUTER = "openrouter"  # OpenRouter universal gateway


# ---------------------------------------------------------------------------
# Player & Move Schemas
# ---------------------------------------------------------------------------

class PlayerConfig(BaseModel):
    """Configuration for an AI player participating in a chess match."""
    name: str = "AI Player"                                # Display name (e.g. "Gemini 2.5 Flash")
    provider: ProviderType                                 # AI service provider
    model_id: str                                          # Exact model identifier string
    temperature: float = 0.7                               # Sampling temperature (0.0 = deterministic, 1.0 = creative)
    thinking_mode: str = "medium"                          # Reasoning effort level: "off", "low", "medium", "high"
    thinking_budget: Optional[int] = None                  # Explicit token budget for thinking models (e.g. 1024, 4096)
    system_prompt: Optional[str] = None                    # Custom instructions (None = default Grandmaster engine)
    color: PlayerColor = PlayerColor.WHITE                 # Assigned side: White or Black


class MoveData(BaseModel):
    """Detailed record of a single executed chess move and the AI's thoughts."""
    move_number: int                       # Full move counter (e.g. 1, 2, 3...)
    turn: PlayerColor                      # Who played this move: White or Black
    san: str                               # Standard Algebraic Notation (e.g. "Nf3", "e4", "O-O", "Qxf7#")
    uci: str                               # Universal Chess Interface format (e.g. "g1f3", "e2e4")
    fen_before: str                        # Board FEN position prior to the move
    fen_after: str                         # Board FEN position resulting after the move
    reasoning: str = ""                    # Full chain-of-thought explanation generated by the AI
    player_name: str                       # Name of the player who made the move
    model_id: str                          # Model ID used for the move
    duration_ms: int = 0                   # Time taken in milliseconds for the AI to compute
    timestamp: str                         # ISO-8601 timestamp of move execution
    is_check: bool = False                 # True if this move placed the opponent king in check
    is_checkmate: bool = False             # True if this move resulted in checkmate
    is_capture: bool = False               # True if this move captured an enemy piece
    captured_piece: Optional[str] = None   # Single-character symbol of captured piece (e.g. "p", "n", "q")


class GameResult(BaseModel):
    """Final outcome summary of a concluded chess game."""
    winner: Optional[PlayerColor] = None   # Winning color, or None if the game was a draw
    reason: str = ""                       # "checkmate", "stalemate", "insufficient_material", "75_moves", etc.
    description: str = ""                  # User-friendly explanation (e.g. "Checkmate! White wins.")


# ---------------------------------------------------------------------------
# Global Game State Schema
# ---------------------------------------------------------------------------

class GameState(BaseModel):
    """Complete snapshot of the active match broadcasted in real-time over WebSockets."""
    game_id: str                                                                         # Unique session ID for the match
    status: GameStatus = GameStatus.IDLE                                                 # Current game lifecycle status
    fen: str = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"                # Standard FEN position string
    turn: PlayerColor = PlayerColor.WHITE                                                # Active side to move
    white_player: Optional[PlayerConfig] = None                                          # Configuration for Player 1 (White)
    black_player: Optional[PlayerConfig] = None                                          # Configuration for Player 2 (Black)
    move_delay_seconds: int = 10                                                         # Delay interval between moves in seconds
    current_move_number: int = 1                                                         # Current turn number
    move_history: List[MoveData] = []                                                    # Chronological list of all played moves
    result: Optional[GameResult] = None                                                  # Concluded match result (if finished)
    captured_by_white: List[str] = []                                                    # Pieces captured by White
    captured_by_black: List[str] = []                                                    # Pieces captured by Black
    pgn: str = ""                                                                        # Complete Portable Game Notation string
    live_thinking: str = ""                                                              # Real-time streaming reasoning text for active turn
    is_thinking: bool = False                                                            # True when the backend is actively generating a move
    thinking_player: Optional[PlayerColor] = None                                        # Which side is currently generating thoughts
    countdown_seconds: Optional[float] = None                                            # Remaining seconds in move delay interval
    last_move_uci: Optional[str] = None                                                  # UCI string of most recent move for UI square highlights


# ---------------------------------------------------------------------------
# Settings & API Payloads
# ---------------------------------------------------------------------------

class ApiKeysConfig(BaseModel):
    """Stored API keys for AI provider access."""
    deepseek_key: str = ""                 # DeepSeek API key (platform.deepseek.com)
    openai_key: str = ""                   # OpenAI API key
    gemini_key: str = ""                   # Google Gemini API key
    anthropic_key: str = ""                # Anthropic API key
    groq_key: str = ""                     # Groq API key
    openrouter_key: str = ""               # OpenRouter API key



class ModelOption(BaseModel):
    """Metadata describing an available AI model for the match roster."""
    id: str                                # Model string passed to LiteLLM (e.g. "gemini/gemini-2.0-flash")
    name: str                              # Friendly display name (e.g. "Gemini 2.0 Flash")
    provider: ProviderType                 # Provider type
    supports_thinking: bool = False        # True if model natively streams chain-of-thought tokens
    description: str = ""                  # Brief description of model characteristics


class SettingsPayload(BaseModel):
    """Full settings payload containing keys, presets, dynamic model definitions, and token optimization preferences."""
    model_config = ConfigDict(populate_by_name=True)

    keys: ApiKeysConfig                    # Stored API credentials
    default_delay: int = 10                # Default move delay in seconds
    models: List[ModelOption] = Field(default_factory=list, alias="custom_models")  # Dynamically synced model list
    include_ascii_board: bool = True       # Whether to include visual 8x8 ASCII board diagram in LLM prompt
    history_context_limit: int = 0         # 0 = Full history; >0 = only send the last N moves to save input tokens
    max_output_tokens: int = 500           # Cap on maximum generation output tokens per turn


class GameControlRequest(BaseModel):
    """Payload for match lifecycle actions (start, pause, resume, step, stop, reset, load)."""
    action: str                            # Action to perform: "start", "pause", "resume", "step", "stop", "reset", "load"
    white_player: Optional[PlayerConfig] = None  # Configuration for White player (required for start)
    black_player: Optional[PlayerConfig] = None  # Configuration for Black player (required for start)
    move_delay_seconds: Optional[int] = 10       # Move delay interval
    game_id: Optional[str] = None          # Saved game ID (for "load" action)


class TestKeyRequest(BaseModel):
    """Payload for validating API key connectivity against a provider."""
    provider: ProviderType                 # Provider to test
    api_key: str                           # Key string to validate
